### ISSUE TITLE
Tirar o apontamento (CNAME) para o domínio grupyba.com.br

### ISSUE THREAD

**Issue by geisasantos** [GruPyBA/encontros#5]
Não acho necessário, no momento termos um domínio próprio.
Se tivermos um sponsor que possa bancar este custo, beleza.

Estou devendo algumas publicações sobre eventos que organizei e registrei, devo fazer em breve.
Está na pauta fazermos um sprint para [resgatar o conteúdo de outros eventos do GruPy-BA](https://github.com/GruPyBA/encontros) e movimentar o "site".

Depois quando tivermos conteúdo podemos planejar migrar do Jekyll para Lektor, Pelican ou outro framework em Python.

O que acham?

**Comment by jrsouza95** [comment]
Concordo, acho legal criar conteúdo primeiro e fazer a migração para o Lektor ou algum outro afim, sendo em Python ta tranquilo 😄 .

**Comment by mauriciovieira** [comment]
> Depois quando tivermos conteúdo podemos planejar migrar do Jekyll para Lektor, Pelican ou outro framework em Python.

Concordo. E isso merece uma nova tarefa :-)

**Comment by RodolfoSilva** [comment]
Feito. http://grupyba.github.io/

**Comment by geisasantos** [comment]
Valeu!
