### ISSUE TITLE
Reunião Aberta GruPy-BA 22/02/19

### ISSUE THREAD

**Issue by geisasantos** [GruPyBA/encontros#6]
## Definição do evento:

- Teaser: Reunião do Grupy-BA simultânea com FSA
- Data: 22/02/19 (Sexta)
- Horário: 20h ~ 22h
- Local: Raul Hackerspace - [Como chegar](http://raulhc.cc/Doc/Sede#ComoChegar)
- Flyer de divulgação: anexado (formato configurado nas medidas do Instagram)
![Reunião GruPy-BA](http://raulhc.cc/pub/Agenda/2019-02-22-ReuniaoGruPy-BA/GruPyBA_22-02-19.png)

## Divulgação do evento:

- [:white_check_mark:] Lista de discussão

- [:white_check_mark:] [Salvador Python Meetup](http://meetu.ps/e/Gq7cB/1Gmcx/f)

- [:white_check_mark:] [Agenda do RaulHC](http://raulhc.cc/Agenda/2019-02-22-ReuniaoGruPy-BA)

- [:white_check_mark:] [Grupo no Facebook](https://www.facebook.com/groups/grupyba/)

- [ ] Twitter do GruPy-Ba (Quem tem acesso? Compartilha lá, pls)

## Mídias sociais

- Link encurtado para compartilhamento: http://meetu.ps/e/Gq7cB/1Gmcx/f
- Citar o Twitter do GruPy-BA (qual é?)
- Usar a hashtag #grupyba

Esqueci algo? Me avisem. 
⚠️ **Grupos de outras cidades que desejem participar, promovendo localmente a reunião, me cita para poder ajudar vocês e também inserir as localidades nas peças de divulgação.**

## Código de Conduta
É importante lembrar sempre de inserir o código de conduta em toda divulgação e também ressaltar no início do evento.

Abaixo alguns recomendados:

- Python Brasil CDC - https://python.org.br/cdc/
- Contributor Convenant - https://www.contributor-covenant.org/pt-br/version/1/4/code-of-conduct
- Codamos - https://www.codamos.club/codigo-de-conduta

## Pauta

Deixem sugestões nos comentários.

Abaixo algumas já sugeridas:

- Ativação de grupos em outras cidades da Bahia
- Organização do Meetup dia 16/03 em Feira de Santana
- Organização de evento para 200 a 300 pessoas em Feira de Santana em junho
- Precisamos de um sprint para colaborar no desenvolvimento do site do GruPy-BA
- Precisamos de um sprint para colaborar no histórico de atividades do GruPy-BA

**Comment by geisasantos** [comment]
Graças, a Matheus CAS, segue a pauta da reunião:

### Grupy-Ba: 22/02/2019

Obs.: O audio estava baixo, então algumas coisas devem/podem ter se perdido

- A [pauta principal de 2017](https://github.com/GruPyBA/encontros/issues/2) se manteve: responsabilidades concentradas em poucas pessoas
- Não é obrigatório ter um Grupy por estado.
- Matheus levantou a questão do Grupy se dividir por regiões/cidades para “dividir e conquistar”
- Fábio citou a intenção de Feira fazer um evento grande em Junho como uma forma de movimentar mais expressivamente Feira e atrair Salvador também - além de outras regiões
- Já vai ter um meetup/workshop antes para tentar movimentar a comunidade local
- Não é obrigatório a chancela da Associação Brasileira de Python para fazer um evento, mas é legal.
- Pra ter grana, é importante que a associação saiba que há interessados e usuários na região
- Novamente, o evento de Junho de Feira é para movimentar toda a comunidade, desde Salvador, Feira e região. 
- Verificar a data do Python Nordeste para não chocar ou ficar muito próximo. 
- Grupy-BA não é Salvador. Está aberto para qualquer cidade fazer um evento em nome do Grupy. 
- Dia 16/03 numa manhã, haverá um evento em FSA com a participação da Geisa.

Presentes:
@geisasantos @luizclaudio @mauriciovieira @rnetonet @elfotux @ZecadoRaulHC
@matheusCAS @FabioBispo @Andressa @MarceloMandacaru
>>quem estava online, coloque seu @ acima

**Comment by mauriciovieira** [comment]
@geisasantos eu acho que a ideia nunca foi registrar as reuniões em issues. a ideia era ser algo como https://github.com/grupy-sp/encontros/blob/master/2018/11-loggi-especial-11-anos-grupy-abc-6meses.md, a partir da issue, um pull request ou um markdown relatando a reunião seria escrito diretamente no repositório.
